In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv('/content/netflix_reviews.csv.zip')

In [ ]:
df.head()

reviewId            userName  \
0  efd00499-5e00-49b5-9f32-bc7177ac5ca6     Mikel Magnusson   
1  be0d97e1-7de1-4f07-b493-35a53098b5a4       John McDevitt   
2  8970dbcd-d75f-4016-bb93-efa5de3ef9e6      Mayur Savaliya   
3  a288bc3c-8a90-42d3-b585-1c8078faa96c  Magdalena Glessing   
4  c388a806-0795-4812-b04e-5b2cdf327157    Elizabeth Turner   

                                             content  score  thumbsUpCount  \
0  Netfix Canada forced my wife into a screen tha...      1              0   
1  I use this app until it asks if I'm still ther...      2              0   
2                        Boycott Netflix from Bharat      1              1   
3  Little good movies and a lot of wonderful TV s...      5              0   
4  New to this but, so far smooth sailing.app is ...      5              0   

     reviewCreatedVersion                   at              appVersion  
0    8.93.1 build 4 50540  2024-06-14 21:47:49    8.93.1 build 4 50540  
1  8.119.0 build 11 50706  2024-06-14 21:33:01  8.119.0 build 11 50706  
2    8.14.0 build 5 40129  2024-06-14 21:31:07    8.14.0 build 5 40129  
3  8.118.1 build 10 50703  2024-06-14 21:27:26  8.118.1 build 10 50703  
4  8.118.1 build 10 50703  2024-06-14 21:22:13  8.118.1 build 10 50703

In [ ]:
import re

In [ ]:
#Preprocessing
def preprocess_text(text):
  if isinstance(text, float):
    return ""
  text = text.lower()
  text = re.sub(r'[^\w\s]', '', text)
  text = re.sub(r'\d+', '', text)
  text = text.strip()
  return text

In [ ]:
df['content_c'] = df['content'].apply(preprocess_text)
df.head()

reviewId            userName  \
0  efd00499-5e00-49b5-9f32-bc7177ac5ca6     Mikel Magnusson   
1  be0d97e1-7de1-4f07-b493-35a53098b5a4       John McDevitt   
2  8970dbcd-d75f-4016-bb93-efa5de3ef9e6      Mayur Savaliya   
3  a288bc3c-8a90-42d3-b585-1c8078faa96c  Magdalena Glessing   
4  c388a806-0795-4812-b04e-5b2cdf327157    Elizabeth Turner   

                                             content  score  thumbsUpCount  \
0  Netfix Canada forced my wife into a screen tha...      1              0   
1  I use this app until it asks if I'm still ther...      2              0   
2                        Boycott Netflix from Bharat      1              1   
3  Little good movies and a lot of wonderful TV s...      5              0   
4  New to this but, so far smooth sailing.app is ...      5              0   

     reviewCreatedVersion                   at              appVersion  \
0    8.93.1 build 4 50540  2024-06-14 21:47:49    8.93.1 build 4 50540   
1  8.119.0 build 11 50706  2024-06-14 21:33:01  8.119.0 build 11 50706   
2    8.14.0 build 5 40129  2024-06-14 21:31:07    8.14.0 build 5 40129   
3  8.118.1 build 10 50703  2024-06-14 21:27:26  8.118.1 build 10 50703   
4  8.118.1 build 10 50703  2024-06-14 21:22:13  8.118.1 build 10 50703   

                                           content_c  
0  netfix canada forced my wife into a screen tha...  
1  i use this app until it asks if im still there...  
2                        boycott netflix from bharat  
3  little good movies and a lot of wonderful tv s...  
4  new to this but so far smooth sailingapp is ea...

In [ ]:
df.isnull().sum()

reviewId                    0
userName                    1
content                     2
score                       0
thumbsUpCount               0
reviewCreatedVersion    16491
at                          0
appVersion              16491
content_c                   0
dtype: int64

In [ ]:
df.fillna('', inplace=True)

In [ ]:
df.isnull().sum()

reviewId                0
userName                0
content                 0
score                   0
thumbsUpCount           0
reviewCreatedVersion    0
at                      0
appVersion              0
content_c               0
dtype: int64

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [ ]:
dtm = cv.fit_transform(df['content_c'])

In [ ]:
dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 1352938 stored elements and shape (113068, 17933)>

LDA

In [ ]:
from sklearn.decomposition import LatentDirichletAllocation

In [ ]:
LDA = LatentDirichletAllocation(n_components=7,random_state=42)

In [ ]:
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

In [ ]:
len(cv.get_feature_names_out())

17933

In [ ]:
import random

In [ ]:
for i in range(10):
    random_word_id = random.randint(0, len(cv.get_feature_names_out()) - 1)
    print(cv.get_feature_names_out()[random_word_id])

bw
regrets
newest
buffring
tablets
film
delayed
فيه
apps
master


In [ ]:
for i in range(10):
    random_word_id = random.randint(0, len(cv.get_feature_names_out()) - 1)
    print(cv.get_feature_names_out()[random_word_id])

unwanted
thatits
peg
peeps
hurry
carribean
fresh
downright
screensaver
scum


In [ ]:
len(LDA.components_)

7

In [ ]:
LDA.components_

array([[0.14316044, 0.14483469, 0.1428572 , ..., 0.1428572 , 0.14285734,
        0.14304626],
       [0.14285723, 0.14300294, 0.14285721, ..., 0.1428572 , 0.14285736,
        0.14285733],
       [0.14314093, 0.14433718, 0.14285721, ..., 0.14318792, 0.14446484,
        0.14327265],
       ...,
       [1.99195736, 4.1316838 , 0.14285727, ..., 0.14285726, 0.14285754,
        0.1428575 ],
       [0.1429983 , 1.14984458, 2.14285669, ..., 3.14214927, 2.14215787,
        0.1428573 ],
       [1.29211801, 0.14285725, 0.1428572 , ..., 0.14285719, 1.14079415,
        2.14172785]])

In [ ]:
len(LDA.components_[0])

17933

In [ ]:
single_topic = LDA.components_[0]

In [ ]:
single_topic.argsort()

array([17032, 13302,  9999, ..., 10249, 11459,   814])

In [ ]:
single_topic[1830]


np.float64(0.14331293237942747)

In [ ]:
single_topic[single_topic.argsort()[-1]]

np.float64(18913.752765987923)

In [ ]:
single_topic.argsort()[-10:]

array([ 8355,  4524,  5879, 10817, 17573, 17588, 16668, 10249, 11459,
         814])

In [ ]:
top_word_indices = single_topic.argsort()[-10:]

In [ ]:
for index in top_word_indices:
    print(cv.get_feature_names_out()[index])

just
doesnt
fix
open
work
working
update
netflix
phone
app


In [ ]:
for index,topic in enumerate(LDA.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([cv.get_feature_names_out()[i] for i in topic.argsort()[-15:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['time', 'play', 'wont', 'works', 'download', 'just', 'doesnt', 'fix', 'open', 'work', 'working', 'update', 'netflix', 'phone', 'app']


THE TOP 15 WORDS FOR TOPIC #1
['going', 'new', 'good', 'use', 'time', 'really', 'watching', 'tv', 'shows', 'dont', 'just', 'like', 'watch', 'im', 'netflix']


THE TOP 15 WORDS FOR TOPIC #2
['dont', 'sign', 'pay', 'use', 'month', 'subscription', 'password', 'try', 'payment', 'money', 'error', 'service', 'app', 'account', 'netflix']


THE TOP 15 WORDS FOR TOPIC #3
['netflix', 'movie', 'issue', 'update', 'playing', 'play', 'watching', 'black', 'brightness', 'fix', 'subtitles', 'audio', 'video', 'app', 'screen']


THE TOP 15 WORDS FOR TOPIC #4
['amazon', 'plan', 'list', 'video', 'watch', 'prime', 'dont', 'hd', 'add', 'content', 'like', 'movie', 'option', 'netflix', 'quality']


THE TOP 15 WORDS FOR TOPIC #5
['available', 'love', 'best', 'better', 'add', 'price', 'great', 'app', 'content', 'like', 'shows', 'series', 'good', 'm

In [ ]:
dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 1352938 stored elements and shape (113068, 17933)>

In [ ]:
dtm.shape

(113068, 17933)

In [ ]:
len(df)

113068

In [ ]:
topic_results = LDA.transform(dtm)

In [ ]:
topic_results.shape

(113068, 7)

In [ ]:
topic_results[0]

array([0.12291897, 0.00367338, 0.6542076 , 0.06675803, 0.00367112,
       0.14509647, 0.00367443])

In [ ]:
topic_results[0].round(2)

array([0.12, 0.  , 0.65, 0.07, 0.  , 0.15, 0.  ])

In [ ]:
topic_results[0].argmax()

np.int64(2)

In [ ]:
df.head()

reviewId            userName  \
0  efd00499-5e00-49b5-9f32-bc7177ac5ca6     Mikel Magnusson   
1  be0d97e1-7de1-4f07-b493-35a53098b5a4       John McDevitt   
2  8970dbcd-d75f-4016-bb93-efa5de3ef9e6      Mayur Savaliya   
3  a288bc3c-8a90-42d3-b585-1c8078faa96c  Magdalena Glessing   
4  c388a806-0795-4812-b04e-5b2cdf327157    Elizabeth Turner   

                                             content  score  thumbsUpCount  \
0  Netfix Canada forced my wife into a screen tha...      1              0   
1  I use this app until it asks if I'm still ther...      2              0   
2                        Boycott Netflix from Bharat      1              1   
3  Little good movies and a lot of wonderful TV s...      5              0   
4  New to this but, so far smooth sailing.app is ...      5              0   

     reviewCreatedVersion                   at              appVersion  \
0    8.93.1 build 4 50540  2024-06-14 21:47:49    8.93.1 build 4 50540   
1  8.119.0 build 11 50706  2024-06-14 21:33:01  8.119.0 build 11 50706   
2    8.14.0 build 5 40129  2024-06-14 21:31:07    8.14.0 build 5 40129   
3  8.118.1 build 10 50703  2024-06-14 21:27:26  8.118.1 build 10 50703   
4  8.118.1 build 10 50703  2024-06-14 21:22:13  8.118.1 build 10 50703   

                                           content_c  
0  netfix canada forced my wife into a screen tha...  
1  i use this app until it asks if im still there...  
2                        boycott netflix from bharat  
3  little good movies and a lot of wonderful tv s...  
4  new to this but so far smooth sailingapp is ea...

In [ ]:
topic_results.argmax(axis=1)

array([2, 4, 4, ..., 4, 5, 6])

In [ ]:
df['content_c'] = topic_results.argmax(axis=1)

In [ ]:
df.head(10)

reviewId            userName  content  score  \
0  efd00499-5e00-49b5-9f32-bc7177ac5ca6     Mikel Magnusson        2      1   
1  be0d97e1-7de1-4f07-b493-35a53098b5a4       John McDevitt        4      2   
2  8970dbcd-d75f-4016-bb93-efa5de3ef9e6      Mayur Savaliya        4      1   
3  a288bc3c-8a90-42d3-b585-1c8078faa96c  Magdalena Glessing        6      5   
4  c388a806-0795-4812-b04e-5b2cdf327157    Elizabeth Turner        6      5   
5  f25e40a1-186d-41f3-b707-7d0f6a809803         Maria Poven        5      2   
6  41c7b7d4-8237-425c-9e97-b855937ead56        Mārcis Šķēls        0      3   
7  a3250817-a9e3-4adf-91ea-d67146244d6f     Maria Brilliant        6      2   
8  0ec19cee-731d-4897-8989-6d9dba9b07eb       Jonathan Gray        0      1   
9  adf1cd65-6264-4cdb-957e-428d9e65a46e       Laura Melling        5      5   

   thumbsUpCount    reviewCreatedVersion                   at  \
0              0    8.93.1 build 4 50540  2024-06-14 21:47:49   
1              0  8.119.0 build 11 50706  2024-06-14 21:33:01   
2              1    8.14.0 build 5 40129  2024-06-14 21:31:07   
3              0  8.118.1 build 10 50703  2024-06-14 21:27:26   
4              0  8.118.1 build 10 50703  2024-06-14 21:22:13   
5              0   8.117.0 build 3 50695  2024-06-14 21:11:51   
6              0  8.113.2 build 27 50674  2024-06-14 21:10:17   
7              0                          2024-06-14 20:59:45   
8              0  8.118.1 build 10 50703  2024-06-14 20:58:19   
9              0   8.117.0 build 3 50695  2024-06-14 20:44:12   

               appVersion  content_c  
0    8.93.1 build 4 50540          2  
1  8.119.0 build 11 50706          4  
2    8.14.0 build 5 40129          4  
3  8.118.1 build 10 50703          6  
4  8.118.1 build 10 50703          6  
5   8.117.0 build 3 50695          5  
6  8.113.2 build 27 50674          0  
7                                  6  
8  8.118.1 build 10 50703          0  
9   8.117.0 build 3 50695          5